In [2]:
import pandas as pd 
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [3]:
df_customerchurn= pd.read_csv('customerchurn.csv')
df_customerchurn

#Analyse the dataset and identify the task to be performed whether it is regression or
#classification
#The task is a classification problem according to the data

gender  Partner  Dependents  PhoneService  MultipleLines  \
0          0        1           0             0              1   
1          1        0           0             1              0   
2          1        0           0             1              0   
3          1        0           0             0              1   
4          0        0           0             1              0   
...      ...      ...         ...           ...            ...   
6882       1        0           0             1              0   
6883       0        1           1             1              0   
6884       0        0           0             1              0   
6885       0        1           0             1              2   
6886       0        1           0             1              2   

      InternetService  OnlineSecurity  DeviceProtection  TechSupport  \
0                   0               0                 0            0   
1                   0               2                 2            0   
2                   0               2                 0            0   
3                   0               2                 2            2   
4                   1               0                 0            0   
...               ...             ...               ...          ...   
6882                1               0                 0            2   
6883                2               1                 1            1   
6884                1               0                 0            0   
6885                1               0                 2            0   
6886                1               0                 0            0   

      StreamingTV  StreamingMovies  Contract  PaperlessBilling  PaymentMethod  \
0               0                0         0                 1              2   
1               0                0         1                 0              3   
2               0                0         0                 1              3   
3               0                0         1                 0              0   
4               0                0         0                 1              2   
...           ...              ...       ...               ...            ...   
6882            2                0         0                 0              2   
6883            1                1         2                 1              0   
6884            2                2         1                 1              3   
6885            2                0         0                 1              2   
6886            0                0         0                 1              1   

      TotalCharges  Churn  SeniorCitizen    tenure  MonthlyCharges  
0             2484      0            0.0  0.013889        0.115423  
1             1454      0            0.0  0.472222        0.385075  
2              155      1            0.0  0.027778        0.354229  
3             1389      0            0.0  0.625000        0.239303  
4              917      1            0.0  0.027778        0.521891  
...            ...    ...            ...       ...             ...  
6882          5806      0            1.0  0.013889        0.572139  
6883          2093      0            0.0  0.527778        0.509950  
6884          2873      0            0.0  0.930556        0.842786  
6885          3328      0            0.0  0.263889        0.601493  
6886          1260      1            0.0  0.166667        0.421891  

[6887 rows x 19 columns]

In [4]:
## y is dependent variable and X is independent variable.
# Load X Variables into a Pandas Dataframe with columns 
y=df_customerchurn['Churn']
X=df_customerchurn.drop(['Churn'],axis=1)
print(y.shape)
print(X.shape)

(6887,)
(6887, 18)


In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)
#1a Split the data into training and testing dataset
#split 

In [6]:
#feature Scaling  
#use standard scaler
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
X_train= st_x.fit_transform(X_train)    
X_test= st_x.transform(X_test) 

In [7]:
#Fitting K-NN classifier to the training set  
from sklearn.svm import SVC
svm_classifier= SVC(kernel='rbf',degree=2,random_state=0)  # Hyper Parameter
svm_classifier.fit(X_train, y_train)  
##1b Build the model using training dataset
#2aModel building


SVC(degree=2, random_state=0)

In [8]:
#Predicting the test set result  
y_pred= svm_classifier.predict(X_test)
print(y_pred)

#1c Make predictions using the built model on test dataset.


[0 0 0 ... 0 0 0]


In [9]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred) 


In [10]:
print(cm)
#print confusion matrix

[[916 102]
 [200 160]]


In [11]:
from sklearn import metrics
print("accuracy",metrics.accuracy_score(y_test,y_pred))

#Compare the accuracy of all 5 models and select the best one.
#SVC 0.780841,Logistic regression 0.783744,Knnclassifier 0.751814,Decisiontreeclassifier 0.722786,Randomforest Classifier0.775761
#Logistic regression has the highest accuracy

accuracy 0.7808417997097242


In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))
#1d Evaluate model using appropriate evaluation metrics 

#print classification report

              precision    recall  f1-score   support

           0       0.82      0.90      0.86      1018
           1       0.61      0.44      0.51       360

    accuracy                           0.78      1378
   macro avg       0.72      0.67      0.69      1378
weighted avg       0.77      0.78      0.77      1378



In [13]:
# Get Support Vector indices
support_vector_indices= svm_classifier.support_
print(support_vector_indices)
#print support vectors

[   0    2    3 ... 5478 5487 5495]


In [14]:
# Get number of support_vector per class
support_vector_per_class= svm_classifier.n_support_
print(support_vector_per_class)

[1601 1317]


In [15]:
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score 
from sklearn.model_selection import KFold
from sklearn import model_selection
kfold = KFold(n_splits=10)
cv_results = model_selection.cross_val_score(svm_classifier, X, y, cv=kfold)

#use kfold 

In [16]:
print(cv_results)

#print cv_results

[0.75907112 0.71407837 0.73004354 0.75181422 0.74310595 0.73004354
 0.74310595 0.72383721 0.7252907  0.72819767]


In [17]:
print(cv_results.mean())

#Print cv_result mean

0.7348588280959935


In [18]:
from sklearn.model_selection import GridSearchCV
parameters = {'C':[0.01,0.05,10,20,30],
              'degree':[2,3,4],
              'gamma':[0.001,0.01],
              'kernel':['rbf']
             }        
c1 = SVC()  
grid = GridSearchCV(c1, parameters, cv=10)
grid.fit(X,y)

## 2b Apply hyperparameter tuning using GridSearchCV for all the models.

GridSearchCV(cv=10, estimator=SVC(),
             param_grid={'C': [0.01, 0.05, 10, 20, 30], 'degree': [2, 3, 4],
                         'gamma': [0.001, 0.01], 'kernel': ['rbf']})

In [19]:
print(grid.best_score_)
print(grid.best_params_)
print(grid.best_estimator_)



0.7567881493232524
{'C': 10, 'degree': 2, 'gamma': 0.001, 'kernel': 'rbf'}
SVC(C=10, degree=2, gamma=0.001)


In [ ]:
import pandas as pd 
from sklearn.linear_model import LogisticRegression
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [20]:
df_customerchurn= pd.read_csv('customerchurn.csv')
df_customerchurn
#Analyse the dataset and identify the task to be performed whether it is regression or classification
#The task is a classification problem according to the data

gender  Partner  Dependents  PhoneService  MultipleLines  \
0          0        1           0             0              1   
1          1        0           0             1              0   
2          1        0           0             1              0   
3          1        0           0             0              1   
4          0        0           0             1              0   
...      ...      ...         ...           ...            ...   
6882       1        0           0             1              0   
6883       0        1           1             1              0   
6884       0        0           0             1              0   
6885       0        1           0             1              2   
6886       0        1           0             1              2   

      InternetService  OnlineSecurity  DeviceProtection  TechSupport  \
0                   0               0                 0            0   
1                   0               2                 2            0   
2                   0               2                 0            0   
3                   0               2                 2            2   
4                   1               0                 0            0   
...               ...             ...               ...          ...   
6882                1               0                 0            2   
6883                2               1                 1            1   
6884                1               0                 0            0   
6885                1               0                 2            0   
6886                1               0                 0            0   

      StreamingTV  StreamingMovies  Contract  PaperlessBilling  PaymentMethod  \
0               0                0         0                 1              2   
1               0                0         1                 0              3   
2               0                0         0                 1              3   
3               0                0         1                 0              0   
4               0                0         0                 1              2   
...           ...              ...       ...               ...            ...   
6882            2                0         0                 0              2   
6883            1                1         2                 1              0   
6884            2                2         1                 1              3   
6885            2                0         0                 1              2   
6886            0                0         0                 1              1   

      TotalCharges  Churn  SeniorCitizen    tenure  MonthlyCharges  
0             2484      0            0.0  0.013889        0.115423  
1             1454      0            0.0  0.472222        0.385075  
2              155      1            0.0  0.027778        0.354229  
3             1389      0            0.0  0.625000        0.239303  
4              917      1            0.0  0.027778        0.521891  
...            ...    ...            ...       ...             ...  
6882          5806      0            1.0  0.013889        0.572139  
6883          2093      0            0.0  0.527778        0.509950  
6884          2873      0            0.0  0.930556        0.842786  
6885          3328      0            0.0  0.263889        0.601493  
6886          1260      1            0.0  0.166667        0.421891  

[6887 rows x 19 columns]

In [21]:
## y is dependent variable and X is independent variable.
# Load X Variables into a Pandas Dataframe with columns 
y=df_customerchurn['Churn']
X=df_customerchurn.drop(['Churn'],axis=1)
print(y.shape)
print(X.shape)

(6887,)
(6887, 18)


In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)
#split into training and testing data
#1a Split the data into testing and training dataset 

In [23]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)


# import Logistic regression
#1b build the model
#2a Model building

C:\Users\ADEX\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [24]:
y_pred=lr.predict(X_test)
print(y_pred)
##1c Make predictions using the built model on test dataset.


[0 0 0 ... 0 0 0]


In [25]:
print("Predicted Values:")
print(y_pred)
print("Actual Values:")
print(y_test)

#print predicted values
#print actual values

Predicted Values:
[0 0 0 ... 0 0 0]
Actual Values:
3243    0
927     0
413     0
1915    0
5459    0
       ..
3660    0
6410    0
2641    0
5795    0
3762    0
Name: Churn, Length: 1378, dtype: int64


In [26]:
d2=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})
d2.head(30)

#actual and predicted dataframe

Actual  Predicted
3243       0          0
927        0          0
413        0          0
1915       0          0
5459       0          0
4462       0          1
2196       1          0
2167       1          1
368        1          1
2076       1          0
1502       1          1
2296       0          0
6874       0          0
5240       0          0
2529       0          0
4678       0          1
3934       0          0
1217       0          0
6037       0          0
2174       0          1
5729       1          1
2619       1          0
5342       0          0
5369       1          1
1373       0          0
6141       0          0
2894       0          0
6870       1          0
6336       0          0
961        0          0

In [27]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)

In [28]:
print(cm)
#print confusion matrix

[[890  95]
 [203 190]]


In [29]:
print("accuracy",metrics.accuracy_score(y_test,y_pred))
#Compare the accuracy of all 5 models and select the best one.
#Compare the accuracy of all 5 models and select the best one.
#SVC 0.780841,Logistic regression 0.783744,Knnclassifier 0.751814,Decisiontreeclassifier 0.722786,Randomforest Classifier0.775761
#Logistic regression has the highest accuracy 

accuracy 0.783744557329463


In [30]:
cf=confusion_matrix(y_test,y_pred)
print(cf)
print("Classification Report for Testing Dataset:")
print(classification_report(y_test,y_pred))


#1d Evaluate model using appropriate evaluation metrics 

#print classification report

[[890  95]
 [203 190]]
Classification Report for Testing Dataset:
              precision    recall  f1-score   support

           0       0.81      0.90      0.86       985
           1       0.67      0.48      0.56       393

    accuracy                           0.78      1378
   macro avg       0.74      0.69      0.71      1378
weighted avg       0.77      0.78      0.77      1378



In [34]:
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler


pipe = make_pipeline(StandardScaler(), LogisticRegression(max_iter=800, solver='saga', tol=0.4))

param_grid = {
    
    'logisticregression__penalty': ['l1', 'l2']
}

# Create GridSearchCV object
grid_search = GridSearchCV(pipe, param_grid, cv=4)

# Fit the model
grid_search.fit(X, y)


#2b Apply hyperparameter tuning using GridSearchCV for all the models.


GridSearchCV(cv=4,
             estimator=Pipeline(steps=[('standardscaler', StandardScaler()),
                                       ('logisticregression',
                                        LogisticRegression(max_iter=800,
                                                           solver='saga',
                                                           tol=0.4))]),
             param_grid={'logisticregression__penalty': ['l1', 'l2']})

In [35]:
print("Best Parameters:", grid_search.best_params_)
print("Best Score:", grid_search.best_score_)


Best Parameters: {'logisticregression__penalty': 'l2'}
Best Score: 0.7717435133801823


In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier  
from sklearn.model_selection import train_test_split
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [37]:
df_customerchurn= pd.read_csv('customerchurn.csv')

In [38]:
df_customerchurn

#Analyse the dataset and identify the task to be performed whether it is regression or classification
#The task is a classification problem according to the data

gender  Partner  Dependents  PhoneService  MultipleLines  \
0          0        1           0             0              1   
1          1        0           0             1              0   
2          1        0           0             1              0   
3          1        0           0             0              1   
4          0        0           0             1              0   
...      ...      ...         ...           ...            ...   
6882       1        0           0             1              0   
6883       0        1           1             1              0   
6884       0        0           0             1              0   
6885       0        1           0             1              2   
6886       0        1           0             1              2   

      InternetService  OnlineSecurity  DeviceProtection  TechSupport  \
0                   0               0                 0            0   
1                   0               2                 2            0   
2                   0               2                 0            0   
3                   0               2                 2            2   
4                   1               0                 0            0   
...               ...             ...               ...          ...   
6882                1               0                 0            2   
6883                2               1                 1            1   
6884                1               0                 0            0   
6885                1               0                 2            0   
6886                1               0                 0            0   

      StreamingTV  StreamingMovies  Contract  PaperlessBilling  PaymentMethod  \
0               0                0         0                 1              2   
1               0                0         1                 0              3   
2               0                0         0                 1              3   
3               0                0         1                 0              0   
4               0                0         0                 1              2   
...           ...              ...       ...               ...            ...   
6882            2                0         0                 0              2   
6883            1                1         2                 1              0   
6884            2                2         1                 1              3   
6885            2                0         0                 1              2   
6886            0                0         0                 1              1   

      TotalCharges  Churn  SeniorCitizen    tenure  MonthlyCharges  
0             2484      0            0.0  0.013889        0.115423  
1             1454      0            0.0  0.472222        0.385075  
2              155      1            0.0  0.027778        0.354229  
3             1389      0            0.0  0.625000        0.239303  
4              917      1            0.0  0.027778        0.521891  
...            ...    ...            ...       ...             ...  
6882          5806      0            1.0  0.013889        0.572139  
6883          2093      0            0.0  0.527778        0.509950  
6884          2873      0            0.0  0.930556        0.842786  
6885          3328      0            0.0  0.263889        0.601493  
6886          1260      1            0.0  0.166667        0.421891  

[6887 rows x 19 columns]

In [39]:
## y is dependent variable and X is independent variable.
# Load X Variables into a Pandas Dataframe with columns 
y=df_customerchurn['Churn']
X=df_customerchurn.drop(['Churn'],axis=1)
print(y.shape)
print(X.shape)

(6887,)
(6887, 18)


In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

##1a Split the data into training and testing dataset

In [41]:
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
X_train= st_x.fit_transform(X_train)    
X_test= st_x.transform(X_test)   

In [42]:
#Fitting K-NN classifier to the training set  
from sklearn.neighbors import KNeighborsClassifier  
KNNclassifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski',p=2)  # Hyper Parameter
KNNclassifier.fit(X_train, y_train)  

# import Logistic regression
#1b build the model
#2a Model building

KNeighborsClassifier()

In [43]:
#Predicting the test set result  
y_pred= KNNclassifier.predict(X_test)
print(y_pred)
##1c Make predictions using the built model on test dataset.


[0 0 0 ... 0 0 0]


In [44]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred) 

In [45]:
print(cm)

[[845 140]
 [202 191]]


In [46]:
from sklearn import metrics
print("accuracy",metrics.accuracy_score(y_test,y_pred))
#Compare the accuracy of all 5 models and select the best one.
#SVC 0.780841,Logistic regression 0.783744,Knnclassifier 0.751814,Decisiontreeclassifier 0.722786,Randomforest Classifier0.775761
#Logistic regression has the highest accuracy

accuracy 0.7518142235123367


In [47]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

#1d Evaluate model using appropriate evaluation metrics 

#print classification report

              precision    recall  f1-score   support

           0       0.81      0.86      0.83       985
           1       0.58      0.49      0.53       393

    accuracy                           0.75      1378
   macro avg       0.69      0.67      0.68      1378
weighted avg       0.74      0.75      0.74      1378



In [48]:
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score 
from sklearn.model_selection import KFold
from sklearn import model_selection
kfold = KFold(n_splits=10)
cv_results = model_selection.cross_val_score(KNNclassifier, X, y, cv=kfold)

C:\Users\ADEX\anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:842: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\ADEX\anaconda\Lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer(estimator, *args, **routed_params.get(name).score)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADEX\anaconda\Lib\site-packages\sklearn\metrics\_scorer.py", line 527, in __call__
    return estimator.score(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADEX\anaconda\Lib\site-packages\sklearn\base.py", line 705, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ^^^^^^^^^^^^^^^
  File "C:\Users\ADEX\anaconda\Lib\site-packages\sklearn\neighbors\_classification.py", line 246, in predict
    if self._fit_m

In [49]:
print(cv_results)

[nan nan nan nan nan nan nan nan nan nan]


In [50]:
print(cv_results.mean())

nan


In [51]:
from sklearn.model_selection import GridSearchCV
parameters = {'n_neighbors': range(30),
              'metric':['manhattan','euclidean']}        
c1 = KNeighborsClassifier()  
grid = GridSearchCV(c1, parameters, cv=10)
grid.fit(X,y)

#2b Apply hyperparameter tuning using GridSearchCV for all the models.


C:\Users\ADEX\anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:824: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\ADEX\anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 813, in _score
    scores = scorer(estimator, X_test, y_test)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADEX\anaconda\Lib\site-packages\sklearn\metrics\_scorer.py", line 527, in __call__
    return estimator.score(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADEX\anaconda\Lib\site-packages\sklearn\base.py", line 705, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ^^^^^^^^^^^^^^^
  File "C:\Users\ADEX\anaconda\Lib\site-packages\sklearn\neighbors\_classification.py", line 246, in predict
    if self._fit_method == "brute" and ArgKminClassMod

InvalidParameterError: The 'n_neighbors' parameter of KNeighborsClassifier must be an int in the range [1, inf) or None. Got 0 instead.

In [52]:
print(grid.best_score_)
print(grid.best_params_)
print(grid.best_estimator_)

nan
{'metric': 'manhattan', 'n_neighbors': 0}
KNeighborsClassifier(metric='manhattan', n_neighbors=0)


In [53]:
import pandas as pd 
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [54]:
df_customerchurn= pd.read_csv('customerchurn.csv')

In [55]:
df_customerchurn

#Analyse the dataset and identify the task to be performed whether it is regression or classification
#The task is a classification problem according to the data

gender  Partner  Dependents  PhoneService  MultipleLines  \
0          0        1           0             0              1   
1          1        0           0             1              0   
2          1        0           0             1              0   
3          1        0           0             0              1   
4          0        0           0             1              0   
...      ...      ...         ...           ...            ...   
6882       1        0           0             1              0   
6883       0        1           1             1              0   
6884       0        0           0             1              0   
6885       0        1           0             1              2   
6886       0        1           0             1              2   

      InternetService  OnlineSecurity  DeviceProtection  TechSupport  \
0                   0               0                 0            0   
1                   0               2                 2            0   
2                   0               2                 0            0   
3                   0               2                 2            2   
4                   1               0                 0            0   
...               ...             ...               ...          ...   
6882                1               0                 0            2   
6883                2               1                 1            1   
6884                1               0                 0            0   
6885                1               0                 2            0   
6886                1               0                 0            0   

      StreamingTV  StreamingMovies  Contract  PaperlessBilling  PaymentMethod  \
0               0                0         0                 1              2   
1               0                0         1                 0              3   
2               0                0         0                 1              3   
3               0                0         1                 0              0   
4               0                0         0                 1              2   
...           ...              ...       ...               ...            ...   
6882            2                0         0                 0              2   
6883            1                1         2                 1              0   
6884            2                2         1                 1              3   
6885            2                0         0                 1              2   
6886            0                0         0                 1              1   

      TotalCharges  Churn  SeniorCitizen    tenure  MonthlyCharges  
0             2484      0            0.0  0.013889        0.115423  
1             1454      0            0.0  0.472222        0.385075  
2              155      1            0.0  0.027778        0.354229  
3             1389      0            0.0  0.625000        0.239303  
4              917      1            0.0  0.027778        0.521891  
...            ...    ...            ...       ...             ...  
6882          5806      0            1.0  0.013889        0.572139  
6883          2093      0            0.0  0.527778        0.509950  
6884          2873      0            0.0  0.930556        0.842786  
6885          3328      0            0.0  0.263889        0.601493  
6886          1260      1            0.0  0.166667        0.421891  

[6887 rows x 19 columns]

In [56]:
## y is dependent variable and X is independent variable.
# Load X Variables into a Pandas Dataframe with columns 
y=df_customerchurn['Churn']
X=df_customerchurn.drop(['Churn'],axis=1)
print(y.shape)
print(X.shape)

(6887,)
(6887, 18)


In [57]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

##1a Split the data into training and testing dataset

In [58]:
DC=DecisionTreeClassifier()
DC=DC.fit(X_train,y_train)

#1b build the model
#2a Model building

In [60]:
y_pred=DC.predict(X_test)
y_pred

##1c Make predictions using the built model on test dataset.


array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [61]:
print("Actual Values:")
print(y_test)
print("Predicted values:")
print(y_pred)

Actual Values:
3243    0
927     0
413     0
1915    0
5459    0
       ..
3660    0
6410    0
2641    0
5795    0
3762    0
Name: Churn, Length: 1378, dtype: int64
Predicted values:
[0 0 0 ... 0 0 1]


In [62]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred) 

In [63]:
print(cm)

#confusion matrix

[[781 204]
 [178 215]]


In [64]:
print("accuracy",metrics.accuracy_score(y_test,y_pred))
#Compare the accuracy of all 5 models and select the best one.
#SVC 0.780841,Logistic regression 0.783744,Knnclassifier 0.751814,Decisiontreeclassifier 0.722786,Randomforest Classifier0.775761
#Logistic regression has the highest accuracy

accuracy 0.7227866473149492


In [65]:
print(classification_report(y_test,y_pred))
#classification report#
#1d Evaluate model using appropriate evaluation metrics 

              precision    recall  f1-score   support

           0       0.81      0.79      0.80       985
           1       0.51      0.55      0.53       393

    accuracy                           0.72      1378
   macro avg       0.66      0.67      0.67      1378
weighted avg       0.73      0.72      0.73      1378



In [67]:
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

clf = DecisionTreeClassifier(random_state=1)

params =  {
    'criterion' : ['gini', 'entropy'],
    'splitter': ['best'],
}
#
# Create gridsearch instance
#
grid = GridSearchCV(estimator=clf,param_grid=params,cv=10)

grid.fit(X_train, y_train)

#2b Apply hyperparameter tuning using GridSearchCV for all the models.


GridSearchCV(cv=10, estimator=DecisionTreeClassifier(random_state=1),
             param_grid={'criterion': ['gini', 'entropy'],
                         'splitter': ['best']})

In [68]:
print(grid.best_params_)

{'criterion': 'entropy', 'splitter': 'best'}


In [69]:
print(grid.best_score_)


0.711747236429632


In [70]:
import pandas as pd 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [71]:
df_customerchurn= pd.read_csv('customerchurn.csv')

In [72]:
df_customerchurn

#Analyse the dataset and identify the task to be performed whether it is regression or classification
#The task is a classification problem according to the data

gender  Partner  Dependents  PhoneService  MultipleLines  \
0          0        1           0             0              1   
1          1        0           0             1              0   
2          1        0           0             1              0   
3          1        0           0             0              1   
4          0        0           0             1              0   
...      ...      ...         ...           ...            ...   
6882       1        0           0             1              0   
6883       0        1           1             1              0   
6884       0        0           0             1              0   
6885       0        1           0             1              2   
6886       0        1           0             1              2   

      InternetService  OnlineSecurity  DeviceProtection  TechSupport  \
0                   0               0                 0            0   
1                   0               2                 2            0   
2                   0               2                 0            0   
3                   0               2                 2            2   
4                   1               0                 0            0   
...               ...             ...               ...          ...   
6882                1               0                 0            2   
6883                2               1                 1            1   
6884                1               0                 0            0   
6885                1               0                 2            0   
6886                1               0                 0            0   

      StreamingTV  StreamingMovies  Contract  PaperlessBilling  PaymentMethod  \
0               0                0         0                 1              2   
1               0                0         1                 0              3   
2               0                0         0                 1              3   
3               0                0         1                 0              0   
4               0                0         0                 1              2   
...           ...              ...       ...               ...            ...   
6882            2                0         0                 0              2   
6883            1                1         2                 1              0   
6884            2                2         1                 1              3   
6885            2                0         0                 1              2   
6886            0                0         0                 1              1   

      TotalCharges  Churn  SeniorCitizen    tenure  MonthlyCharges  
0             2484      0            0.0  0.013889        0.115423  
1             1454      0            0.0  0.472222        0.385075  
2              155      1            0.0  0.027778        0.354229  
3             1389      0            0.0  0.625000        0.239303  
4              917      1            0.0  0.027778        0.521891  
...            ...    ...            ...       ...             ...  
6882          5806      0            1.0  0.013889        0.572139  
6883          2093      0            0.0  0.527778        0.509950  
6884          2873      0            0.0  0.930556        0.842786  
6885          3328      0            0.0  0.263889        0.601493  
6886          1260      1            0.0  0.166667        0.421891  

[6887 rows x 19 columns]

In [73]:
## y is dependent variable and X is independent variable.
# Load X Variables into a Pandas Dataframe with columns 
y=df_customerchurn['Churn']
X=df_customerchurn.drop(['Churn'],axis=1)
print(y.shape)
print(X.shape)

(6887,)
(6887, 18)


In [74]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)
##1a Split the data into training and testing dataset

In [75]:
rfclassifier=RandomForestClassifier()
rfclassifier=rfclassifier.fit(X_train,y_train)
#1b build the model
#2a Model building

In [81]:
y_pred=rfclassifier.predict(X_test)
##1c Make predictions using the built model on test dataset.



In [77]:
print("Actual Values:")
print(y_test)
print("Predicted values:")
print(y_pred)

Actual Values:
3243    0
927     0
413     0
1915    0
5459    0
       ..
3660    0
6410    0
2641    0
5795    0
3762    0
Name: Churn, Length: 1378, dtype: int64
Predicted values:
[0 0 0 ... 0 0 0]


In [78]:
d2=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})
d2.head(30)

#actual and predicted dataframe

Actual  Predicted
3243       0          0
927        0          0
413        0          0
1915       0          0
5459       0          0
4462       0          0
2196       1          0
2167       1          1
368        1          1
2076       1          0
1502       1          1
2296       0          0
6874       0          0
5240       0          0
2529       0          0
4678       0          1
3934       0          0
1217       0          0
6037       0          0
2174       0          1
5729       1          1
2619       1          0
5342       0          0
5369       1          1
1373       0          0
6141       0          0
2894       0          0
6870       1          0
6336       0          0
961        0          0

In [82]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)

In [83]:
print(cm)

#confusion matrix

[[898  87]
 [222 171]]


In [84]:
print("accuracy",metrics.accuracy_score(y_test,y_pred))

#Compare the accuracy of all 5 models and select the best one.
#Compare the accuracy of all 5 models and select the best one.
#SVC 0.780841,Logistic regression 0.783744,Knnclassifier 0.751814,Decisiontreeclassifier 0.722786,Randomforest Classifier 0.775761
#Logistic regression has the highest accuracy


accuracy 0.7757619738751814


In [85]:
print(classification_report(y_test,y_pred))

#classification report#
#1d Evaluate model using appropriate evaluation metrics 

              precision    recall  f1-score   support

           0       0.80      0.91      0.85       985
           1       0.66      0.44      0.53       393

    accuracy                           0.78      1378
   macro avg       0.73      0.67      0.69      1378
weighted avg       0.76      0.78      0.76      1378



In [86]:
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score 
from sklearn.model_selection import KFold
from sklearn import model_selection
kf = KFold(n_splits=7)
cv_results = model_selection.cross_val_score(rfclassifier, X, y, cv=kf)

In [87]:
print(cv_results)
#print cv result

[0.78252033 0.78760163 0.80182927 0.75609756 0.7703252  0.7652439
 0.78535097]


In [88]:
print(cv_results.mean())
#cvresult mean

0.7784241218011657


In [89]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn import metrics


rfc=RandomForestClassifier()

forest_params =  {
    'n_estimators': [5,11,16],
    'criterion' : ['gini', 'entropy']
}


grid = GridSearchCV(rfc, forest_params, cv = 6, scoring='accuracy')

grid.fit(X_train, y_train)


#2b Apply hyperparameter tuning using GridSearchCV for all the models.


GridSearchCV(cv=6, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'n_estimators': [5, 11, 16]},
             scoring='accuracy')

In [90]:
print(grid.best_params_)


{'criterion': 'gini', 'n_estimators': 16}


In [91]:
print(grid.best_score_)


0.7709211964316617


In [92]:
#2c Create a dataframe to store the result of GridSearchCV for all the models which
#will includes model_name, best_score_ and best_params_
import pandas as pd

    
data =  {'ModelName': ['LogisticRegression'],

        'BestScore': [0.771743],

        'BestParameters': ['Penalty' 'l2']}

In [93]:
df1=pd.DataFrame.from_dict(data, orient='columns')
df1

ModelName  BestScore BestParameters
0  LogisticRegression   0.771743      Penaltyl2

In [94]:
data1 =  {'ModelName': ['DecisionTreeClassifier'],

        'BestScore': [0.711747],

        'BestParameters': ['Criterion' 'Entropy' 'Splitter' 'Best']}

In [95]:
df2=pd.DataFrame.from_dict(data1, orient='columns')
df2

ModelName  BestScore                BestParameters
0  DecisionTreeClassifier   0.711747  CriterionEntropySplitterBest

In [96]:
data2 =  {'ModelName': ['SVC'],

        'BestScore': [0.756788],

        'BestParameters': ['C' '10' 'Degree' '2' 'gamma' '0.001' 'kernel' 'rbf']}

In [97]:
df3=pd.DataFrame.from_dict(data2, orient='columns')
df3

ModelName  BestScore                 BestParameters
0       SVC   0.756788  C10Degree2gamma0.001kernelrbf

In [98]:
data3=  {'ModelName': ['KNeighbourClassifier'],

        'BestScore': [0.000000],

        'BestParameters': ['Metric Manhattan' 'n_neighbours' '0']}

In [99]:
df4=pd.DataFrame.from_dict(data3, orient='columns')
df4

ModelName  BestScore                 BestParameters
0  KNeighbourClassifier        0.0  Metric Manhattann_neighbours0

In [100]:
data4=  {'ModelName': ['RandomForestClassfier'],

        'BestScore': [0.770921],

        'BestParameters': ['Criterion' 'Gini' 'n_estimator' '16']}

In [101]:
df5=pd.DataFrame.from_dict(data4, orient='columns')
df5

ModelName  BestScore              BestParameters
0  RandomForestClassfier   0.770921  CriterionGinin_estimator16

In [102]:
df= pd.concat([df1,df2,df3,df4,df5], ignore_index=True)

In [103]:
df
#2c Create a dataframe to store the result of GridSearchCV for all the models which
#will includes model_name, best_score_ and best_params_

#Dataframe created

ModelName  BestScore                 BestParameters
0      LogisticRegression   0.771743                      Penaltyl2
1  DecisionTreeClassifier   0.711747   CriterionEntropySplitterBest
2                     SVC   0.756788  C10Degree2gamma0.001kernelrbf
3    KNeighbourClassifier   0.000000  Metric Manhattann_neighbours0
4   RandomForestClassfier   0.770921     CriterionGinin_estimator16

In [ ]:
#3 • Write conclusion to indicate your learning from part 1 and part 2 of the project.

#This dataset is about about churn and  according to analysis, I discovered that it is a classification problem. 
#Churn is the dependent variable(y)while others are the independent variable(X). 
#The data was cleaned before splitting into training and testing dataset.
#According to the analysis, Logistic regression has the highest accuracy with a value of 0.783744. 5 classification models were built and 
#predictions were made.


<h3 style='color:red'> # Comments </h3>
    <h4 style='color:red'> 1)Part 1 (25 marks)  </h4> 
<h5 style='color:blue'> 

<br>--- Learner has identified whether the task at hand is a classification or a regression issue.</br>
<br>---Learner has performed data splitting</br>
<br>---Learner has performed the model-building on all 5 Classification Models. </br> 
<br>---There is one suggestion, instead of importing libraries again and again for every model, you can import it only once. This will help reduce the lines of code.</br>
<br>---Comparison of all the models using appropriate evaluation metrics for Part-1 of the project is missing. </br>
<br>---The best model has not been selected for Part-1 of the project.
</h5>
<h5 style='color:green'>                                   
    <u> Marks scored:18 </u><br/>
-----------------------------------------------------------------------------------------------------------------------------------------------------------------    
</h5>    
 
<h3 style='color:red'> # Comments </h3>
    <h4 style='color:red'> 2)Part 2 (30 marks)  </h4> 
<h5 style='color:blue'>                                                                                
<b5>---Learner has provided the code to build 5 ML models and used GridSearchCV. </br>
<b5>---Leaner has performed the activity of hyperparameter tuning on all the 5 models.</br> 
<b5>---Dataframe from all the models alongwith best parameters has been created.</br> 
<b5>---It shows that the best score for KNearestBeignbour is 0. This output is incorrect as the accuracy cannot be zero.</br>
    
<h5 style='color:green'>                                   
<u> Marks scored:20 </u><br/>
-----------------------------------------------------------------------------------------------------------------------------------------------------------------    
</h5> 
</h5> 

<h3 style='color:red'> # Comments </h3>
    <h4 style='color:red'> 3)Part 3 (5 marks)  </h4> 
<h5 style='color:blue'>                                                                                
<br>---Learner has provided the conclusion.</br>
<br>---However, it would have been appreciated if the comments were elaborate. For instance, you could have broken your project into Part-1 and Part-2 which would make your code look better.</br>
<h5 style='color:green'>                                   
<u> Marks scored: 3 </u><br/>
-----------------------------------------------------------------------------------------------------------------------------------------------------------------    
</h5> 
    
<h3 style='color:red'> # Comments </h3>
    <h4 style='color:red'> Overall Comments and Total Marks:</h4>
    
<h5 style='color:blue'>                                                                                
---Congratulations. You have successfully completed this project.</br>
<h5 style='color:green'>                                   
<u> Marks scored:41 </u><br/>
-----------------------------------------------------------------------------------------------------------------------------------------------------------------    
</h5> 